export const VIEW_ORDER_DETAIL = 'VIEW_ORDER_DETAIL';
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const ADD_TO_CART = 'ADD_TO_CART';
export const LOAD_CART = 'LOAD_CART';
export const UPDATE_CART = 'UPDATE_CART';
export const UPDATE_PRICE_ON_CART = 'UPDATE_PRICE_ON_CART';

export const LOADING_PAYMENT_GATEWAY = 'LOADING_PAYMENT_GATEWAY';
export const LOAD_LIST_PRODUCT = 'LOAD_LIST_PRODUCT';
export const UPDATE_PAGE_LIST_PRODUCT = 'UPDATE_PAGE_LIST_PRODUCT';
export const FETCH_USER_DATA = 'FETCH_USER_DATA';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const ADD_PAYMENT_INFO = 'ADD_PAYMENT_INFO';
export const CHANGE_PAYMENT_METHOD = 'CHANGE_PAYMENT_METHOD';
export const UPDATE_PAYMENT_INFOR = 'UPDATE_PAYMENT_INFOR';
export const UPDATE_PAYMENT_TERM = 'UPDATE_PAYMENT_TERM';
export const FETCH_GENERAL_SETTING = 'FETCH_GENERAL_SETTING';
export const FETCH_SHIPPING_SETTING = 'FETCH_SHIPPING_SETTING';
export const FETCH_PAYMENT_GATEWAY_SETTING = 'FETCH_PAYMENT_GATEWAY_SETTING';
export const FETCH_SHIPPING_LOCATIONS_SETTING =
  'FETCH_SHIPPING_LOCATIONS_SETTING';
export const FETCH_SHIPPING_METHODS_SETTING = 'FETCH_SHIPPING_METHODS_SETTING';
export const FETCH_SHIPPING_ZONE_SETTING = 'FETCH_SHIPPING_ZONE_SETTING';
export const ADD_SHIPPING_LINES = 'ADD_SHIPPING_LINES';
export const ADD_SHIPPING_METHOD = 'ADD_SHIPPING_METHOD';
export const UPDATE_SHIPPING_ADDRESS = 'UPDATE_SHIPPING_ADDRESS';

export const bookingActions = {};
