export const VIEW_ORDER_DETAIL = 'VIEW_ORDER_DETAIL';
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const ADD_TO_CART = 'REMOVE_FROM_CART';
export const LOAD_CART = 'LOAD_CART';
